apply plugin: 'com.android.library'

android {
    namespace 'net.pierrox.lightning_launcher.plugin'
    compileSdk 35

    defaultConfig {
        minSdk 21
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}

dependencies {
    api 'com.josesamuel:remoter-annotations:1.2.0'
    annotationProcessor 'com.josesamuel:remoter:1.2.0'
    api 'org.parceler:parceler-api:1.1.12'
    annotationProcessor 'org.parceler:parceler:1.1.12'
}
